#ifndef PRINTFFHEADER
#define PRINTFFHEADER
#include <stdio.h>
#include <stdbool.h>
#include <stdarg.h>

#define VOIDP_ANN 0
#define CHRP_ANN 1
#define INT_ANN 2
#define UINT_ANN 3
#define SHORT_ANN 4
#define USHORT_ANN 5
#define CHAR_ANN 6
#define UCHAR_ANN 7
#define LONG_ANN 8
#define ULONG_ANN 9
#define LONGLONG_ANN 10
#define ULONGLONG_ANN 11
#define FLOAT_ANN 12
#define DOUBLE_ANN 14

#define _ANNOTATE(X) _Generic((X), default: VOIDP_ANN, char *: CHRP_ANN, int: INT_ANN, \
								unsigned int: UINT_ANN, short: SHORT_ANN, unsigned short: USHORT_ANN, \
								char: CHAR_ANN, unsigned char: UCHAR_ANN, long: LONG_ANN, unsigned long: ULONG_ANN, \
								long long: LONGLONG_ANN, unsigned long long: ULONGLONG_ANN, \
								float: FLOAT_ANN, double: DOUBLE_ANN), X




#define _PRINTFF1(fmt) printff_func(fmt)

#define _PRINTFF2(fmt,a) printff_func(fmt,_ANNOTATE(a))

#define _PRINTFF3(fmt,a,b) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b))

#define _PRINTFF4(fmt,a,b,c) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c))

#define _PRINTFF5(fmt,a,b,c,d) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d))

#define _PRINTFF6(fmt,a,b,c,d,e) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e))

#define _PRINTFF7(fmt,a,b,c,d,e,f) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f))

#define _PRINTFF8(fmt,a,b,c,d,e,f,g) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g))

#define _PRINTFF9(fmt,a,b,c,d,e,f,g,h) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h))

#define _PRINTFF10(fmt,a,b,c,d,e,f,g,h,i) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i))

#define _PRINTFF11(fmt,a,b,c,d,e,f,g,h,i,j) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j))

#define _PRINTFF12(fmt,a,b,c,d,e,f,g,h,i,j,k) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k))

#define _PRINTFF13(fmt,a,b,c,d,e,f,g,h,i,j,k,l) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l))

#define _PRINTFF14(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m))

#define _PRINTFF15(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n))

#define _PRINTFF16(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o))

#define _PRINTFF17(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p))

#define _PRINTFF18(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q))

#define _PRINTFF19(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r))

#define _PRINTFF20(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s))

#define _PRINTFF21(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t))

#define _PRINTFF22(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u))

#define _PRINTFF23(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v))

#define _PRINTFF24(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w))

#define _PRINTFF25(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x))

#define _PRINTFF26(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y))

#define _PRINTFF27(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z))

#define _PRINTFF28(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A))

#define _PRINTFF29(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B))

#define _PRINTFF30(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C))

#define _PRINTFF31(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D))

#define _PRINTFF32(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E))

#define _PRINTFF33(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F))

#define _PRINTFF34(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G))

#define _PRINTFF35(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H))

#define _PRINTFF36(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I))

#define _PRINTFF37(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J))

#define _PRINTFF38(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K))

#define _PRINTFF39(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L))

#define _PRINTFF40(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M))

#define _PRINTFF41(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N))

#define _PRINTFF42(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O))

#define _PRINTFF43(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P))

#define _PRINTFF44(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P),_ANNOTATE(Q))

#define _PRINTFF45(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P),_ANNOTATE(Q),_ANNOTATE(R))

#define _PRINTFF46(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P),_ANNOTATE(Q),_ANNOTATE(R),_ANNOTATE(S))

#define _PRINTFF47(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P),_ANNOTATE(Q),_ANNOTATE(R),_ANNOTATE(S),_ANNOTATE(T))

#define _PRINTFF48(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P),_ANNOTATE(Q),_ANNOTATE(R),_ANNOTATE(S),_ANNOTATE(T),_ANNOTATE(U))

#define _PRINTFF49(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P),_ANNOTATE(Q),_ANNOTATE(R),_ANNOTATE(S),_ANNOTATE(T),_ANNOTATE(U),_ANNOTATE(V))

#define _PRINTFF50(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P),_ANNOTATE(Q),_ANNOTATE(R),_ANNOTATE(S),_ANNOTATE(T),_ANNOTATE(U),_ANNOTATE(V),_ANNOTATE(W))

#define _PRINTFF51(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P),_ANNOTATE(Q),_ANNOTATE(R),_ANNOTATE(S),_ANNOTATE(T),_ANNOTATE(U),_ANNOTATE(V),_ANNOTATE(W),_ANNOTATE(X))

#define _PRINTFF52(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P),_ANNOTATE(Q),_ANNOTATE(R),_ANNOTATE(S),_ANNOTATE(T),_ANNOTATE(U),_ANNOTATE(V),_ANNOTATE(W),_ANNOTATE(X),_ANNOTATE(Y))

#define _PRINTFF53(fmt,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z) printff_func(fmt,_ANNOTATE(a),_ANNOTATE(b),_ANNOTATE(c),_ANNOTATE(d),_ANNOTATE(e),_ANNOTATE(f),_ANNOTATE(g),_ANNOTATE(h),_ANNOTATE(i),_ANNOTATE(j),_ANNOTATE(k),_ANNOTATE(l),_ANNOTATE(m),_ANNOTATE(n),_ANNOTATE(o),_ANNOTATE(p),_ANNOTATE(q),_ANNOTATE(r),_ANNOTATE(s),_ANNOTATE(t),_ANNOTATE(u),_ANNOTATE(v),_ANNOTATE(w),_ANNOTATE(x),_ANNOTATE(y),_ANNOTATE(z),_ANNOTATE(A),_ANNOTATE(B),_ANNOTATE(C),_ANNOTATE(D),_ANNOTATE(E),_ANNOTATE(F),_ANNOTATE(G),_ANNOTATE(H),_ANNOTATE(I),_ANNOTATE(J),_ANNOTATE(K),_ANNOTATE(L),_ANNOTATE(M),_ANNOTATE(N),_ANNOTATE(O),_ANNOTATE(P),_ANNOTATE(Q),_ANNOTATE(R),_ANNOTATE(S),_ANNOTATE(T),_ANNOTATE(U),_ANNOTATE(V),_ANNOTATE(W),_ANNOTATE(X),_ANNOTATE(Y),_ANNOTATE(Z))

#define _OVERRIDE_PRINTFF(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,NAME,...) NAME

#define printff(...) _OVERRIDE_PRINTFF(__VA_ARGS__,  _PRINTFF52 , _PRINTFF51 , _PRINTFF50 , _PRINTFF49 , _PRINTFF48 , _PRINTFF47 , _PRINTFF46 , _PRINTFF45 , _PRINTFF44 , _PRINTFF43 , _PRINTFF42 , _PRINTFF41 , _PRINTFF40 , _PRINTFF39 , _PRINTFF38 , _PRINTFF37 , _PRINTFF36 , _PRINTFF35 , _PRINTFF34 , _PRINTFF33 , _PRINTFF32 , _PRINTFF31 , _PRINTFF30 , _PRINTFF29 , _PRINTFF28 , _PRINTFF27 , _PRINTFF26 , _PRINTFF25 , _PRINTFF24 , _PRINTFF23 , _PRINTFF22 , _PRINTFF21 , _PRINTFF20 , _PRINTFF19 , _PRINTFF18 , _PRINTFF17 , _PRINTFF16 , _PRINTFF15 , _PRINTFF14 , _PRINTFF13 , _PRINTFF12 , _PRINTFF11 , _PRINTFF10 , _PRINTFF9 , _PRINTFF8 , _PRINTFF7 , _PRINTFF6 , _PRINTFF5 , _PRINTFF4 , _PRINTFF3 , _PRINTFF2 , _PRINTFF1 )(__VA_ARGS__)

#define _print_type_helper switch (va_arg(argp, int)) { \
					case VOIDP_ANN: l += printf("%p", va_arg(argp, void*)); \
					break; \
					case CHRP_ANN: l += printf("%s", va_arg(argp, char*)); \
					break; \
					case INT_ANN: l += printf("%d", va_arg(argp, int)); \
					break; \
					case UINT_ANN: l += printf("%u", va_arg(argp, unsigned int)) ; \
					break; \
					case SHORT_ANN: l += printf("%hi", va_arg(argp, int)); \
					break; \
					case USHORT_ANN: l += printf("%hu", va_arg(argp, int)); \
					break; \
					case CHAR_ANN: l += printf("%c", va_arg(argp, int)); \
					break; \
					case UCHAR_ANN: l += printf("%c", va_arg(argp, int)); \
					break; \
					case LONG_ANN: l += printf("%ld", va_arg(argp, long)); \
					break; \
					case ULONG_ANN: l += printf("%lu", va_arg(argp, unsigned long)); \
					break; \
					case LONGLONG_ANN: l += printf("%lld", va_arg(argp, long long)); \
					break; \
					case ULONGLONG_ANN: l += printf("%llu", va_arg(argp, unsigned long long)); \
					break; \
					case FLOAT_ANN:  \
					case DOUBLE_ANN: l += printf("%f", va_arg(argp, double)); \
				} \

int printff_func(char * fmt, ...) {
	va_list argp;
	va_start(argp, fmt);
	int l = 0;
	while (*fmt) {
		if (*fmt == '%') {
			fmt++;
			_print_type_helper
			
			if (*fmt != '%') {
							
			}
			else {
				putchar(*fmt++);
				l++;
			}
		}
		else {
			putchar(*fmt++);
			l++;
		}
	}
	va_end(argp);
	return l;
}





#endif